# Generated by Django 4.1.3 on 2022-11-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_category_categorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremotionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
